config/routes.rb
IbRails::Application.routes.draw do
  resources :topics do
    resources :replies
  end

end

app/models/reply.rb
class Reply < ActiveRecord::Base

  validates :topic_id, :content, :created_by_id, presence: true

  belongs_to :topic
  belongs_to :created_by, :class_name => 'User',  :foreign_key => 'created_by_id'
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  validates :title, :content, :created_by_id, presence: true
  belongs_to :created_by, :class_name => 'User',  :foreign_key => 'created_by_id'
  has_many :replies
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, :language, presence: true
  validates :name, uniqueness: true

  has_many :topics
  has_many :replies

  def to_s
    self.name
  end

  def self.default
    User.first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_gettext_locale
  before_filter :set_locale

  def set_locale

    if params[:locale]
      session[:locale] = params[:locale]

    end
    I18n.locale = session[:locale] || I18n.default_locale

    def I18n.rtl?
      I18n.locale.to_s.in? ['he','ar']
    end

  end

end

app/controllers/replies_controller.rb
class RepliesController < ApplicationController
  before_action :set_reply, only: [:show, :edit, :update, :destroy]

  # GET /replies
  # GET /replies.json
  def index
    @replies = Reply.all
  end

  # GET /replies/1
  # GET /replies/1.json
  def show
  end

  # GET /replies/new
  def new
    @topic = Topic.find params[:topic_id]
    @reply = Reply.new(:topic=>@post)
  end

  # GET /replies/1/edit
  def edit
  end

  # POST /replies
  # POST /replies.json
  def create
    topic = Topic.find params[:topic_id]
    @reply = Reply.new(reply_params)
    @reply.topic = topic
    @reply.created_by = User.default



    respond_to do |format|
      if @reply.save

        Pusher["topic_#{topic.id}"].trigger('reply', {:message => @reply})

        format.html { redirect_to topic, notice: 'Reply was successfully created.' }
        format.json { render action: 'show', status: :created, location: @reply }

      else
        format.html { render action: 'new' }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /replies/1
  # PATCH/PUT /replies/1.json
  def update
    respond_to do |format|
      if @reply.update(reply_params)
        format.html { redirect_to @reply, notice: 'Reply was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @reply.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /replies/1
  # DELETE /replies/1.json
  def destroy
    @reply.destroy
    respond_to do |format|
      format.html { redirect_to replies_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reply
      @reply = Reply.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reply_params
      params.require(:reply).permit(:topic_id, :content, :created_by_id)
    end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :set_topic, only: [:show, :edit, :update, :destroy]

  # GET /topics
  # GET /topics.json
  def index
    @topics = Topic.all
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    respond_to do |format|
      format.html
      format.json
      format.xlsx
    end
  end

  # GET /topics/new
  def new
    @topic = Topic.new
  end

  # GET /topics/1/edit
  def edit
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = Topic.new(topic_params)
    @topic.created_by = User.default

    respond_to do |format|
      if @topic.save
        format.html { redirect_to @topic, notice: 'Topic was successfully created.' }
        format.json { render action: 'show', status: :created, location: @topic }
      else
        format.html { render action: 'new' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /topics/1
  # PATCH/PUT /topics/1.json
  def update
    respond_to do |format|
      if @topic.update(topic_params)
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic.destroy
    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_topic
      @topic = Topic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def topic_params
      params.require(:topic).permit(:title, :content, :created_by_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/replies_helper.rb
module RepliesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/layouts/_language.html.erb
<div class='btn-group ib-languages'>
  <% FastGettext.available_locales.each do |locale| %>
      <a class='btn btn-small btn-info' data-no-turbolink href='?locale=<%= locale %>'><%= locale %></a>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>' dir='<%= I18n.rtl? ? 'rtl' : 'ltr' %>'>
<head>
  <title>IbRails</title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-inverse navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="brand" href="#">Ideablog Rails</a>

      <div class="nav-collapse collapse">
        <ul class="nav">
          <li class="active"><%= link_to 'Topics', topics_path %></li>
        </ul>
      </div>

      <%= render "layouts/language" %>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>
<!-- /container -->
</body>
</html>

app/views/replies/_form.html.erb
<%= form_for [@topic, @reply] do |f| %>
  <% if @reply.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reply.errors.count, "error") %> prohibited this reply from being saved:</h2>

      <ul>
      <% @reply.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.text_area :content, :class => "tinymce"%>
    <%= tinymce %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn' %>
    <%= link_to 'Back', back_path, class: 'btn'%>
  </div>
<% end %>

app/views/replies/edit.html.erb
<h1>Editing reply</h1>

<%= render 'form' %>

<%= link_to 'Show', @reply %> |
<%= link_to 'Back', topic_replies_path %>

app/views/replies/index.html.erb
<h1>Listing replies</h1>

<table>
  <thead>
    <tr>
      <th>Topic</th>
      <th>Content</th>
      <th>Created by</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @replies.each do |reply| %>
      <tr>
        <td><%= reply.topic %></td>
        <td><%= reply.content %></td>
        <td><%= reply.created_by %></td>
        <td><%= link_to 'Show', reply %></td>
        <td><%= link_to 'Edit', edit_reply_path(reply) %></td>
        <td><%= link_to 'Destroy', reply, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reply', new_reply_path %>

app/views/replies/new.html.erb
<h1>New reply to <%=@topic.title%></h1>

<%= render 'form', :back_path=>(topic_path @topic) %>

app/views/replies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Topic:</strong>
  <%= @reply.topic %>
</p>

<p>
  <strong>Content:</strong>
  <%= @reply.content %>
</p>

<p>
  <strong>Created by:</strong>
  <%= @reply.created_by %>
</p>

<%= link_to 'Edit', edit_reply_path(@reply) %> |
<%= link_to 'Back', topic_replies_path %>

app/views/topics/_form.html.erb
<%= form_for(@topic) do |f| %>
  <% if @topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@topic.errors.count, "error") %> prohibited this topic from being saved:</h2>

      <ul>
      <% @topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.text_area :content, :class => "tinymce" %>
    <%= tinymce %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1><%=_('Listing topics')%></h1>

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @topics.each do |topic| %>
      <tr>
        <td><%= topic.title %></td>
        <td>
            <%= link_to 'Show', topic, class: 'btn btn-mini' %>
            <%= link_to 'Edit', edit_topic_path(topic), class: 'btn btn-mini' %>
            <%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-mini' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to 'New Topic', new_topic_path, class: 'btn btn-primary' %>

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @topic.title %></h1>
<p class='muted text-right'><%= @topic.created_by %></p>
<p>
  <%= @topic.content.html_safe %>
</p>
<div class='btn-group'>
  <%= link_to 'Add reply', new_topic_reply_path(@topic), class: 'btn btn-primary'%> |
  <%= link_to 'Download XLSX', topic_path(@topic, :format=>:xlsx), class: 'btn' %>
  <%= link_to 'Back', topics_path, class: 'btn' %>
</div>
<div class='replies'>
<% @topic.replies.reverse.each do |reply| %>
    <article class='reply'>
      <!--<p class='muted text-right'><%=_("Created by #{reply.created_by} on #{reply.created_at}")%></p>-->
      <%= reply.content.html_safe %>
    </article>
<% end %>
</div>
<script>
    var pusher = new Pusher('1bf22438f25509d64e77')
    var channel = pusher.subscribe('<%="topic_#{@topic.id}"%>')
    channel.bind('reply', function(data){
        $('<article/>').addClass('reply').html(data.message.content).prependTo('.replies')
        })
</script>